spring:
    data:
        mongodb:
            testdb:
                uri: mongodb://testdb:testdb@10.10.6.133:65000/testdb
            testdb2:
                uri: mongodb://aladinqpjldata:aladinqpjldata@10.10.6.134:65000/aladinqpjldata


